backend:
  name: git-gateway
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/services/services.md"
        label: "Services Page"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "hidden", default: "services"}
          - {label: "Services Content", name: "body", widget: "markdown"}




      # - label: Services
      #   name: services
      #   file: "content/services/services.md"
      #   fields:
      #     - {label: Services, name: services, widget: markdown}